[package]
name = "compiler"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
paste = "1.0"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"]}

[dev-dependencies]
trybuild = { path = "../trybuild" }
macrotest = "1.0"
